### ISSUE TITLE
Maintainer required?

### ISSUE THREAD

**Issue by oystersauce8** [whacked/ob-shstream#2]
Does this script/package have a maintainer?

**Comment by whacked** [comment]
I have not used this since posting it, so no. `:session` handles most of my needs now. If you want to take over you are welcome to.

**Comment by oystersauce8** [comment]
> :session handles most of my needs now

@whacked When you said "most of my needs" does that include the ability to tail/stream the output of bash code blocks?

When you run this, 
```
#+BEGIN_SRC sh :session session1
echo "hello"
sleep 1
echo "hello"
sleep 1
echo "hello"
sleep 1
#+END_SRC
```

,how long do you have to wait for the word hello to appear on your screen.
From what I understand (please correct me if I'm wrong), without ob-shstream,
you would have to wait three seconds to see any output from the block.
With ob-shstream, you can see the first hello immediately.

**Comment by whacked** [comment]
you're probably right. I usually use a session with https://github.com/kaz-yos/eval-in-repl

**Comment by whacked** [comment]
ok on emacs `25.1.1` and org `8.2.10` and `9.1.6` at least, you are correct about the behavior, because as far as these versions are concerned, the execution in `ob-sh` is synchronous. In fact, your example doesn't execute on my system due to my sh session being mangled by special characters :-)

The same example works for me using `shstream`, as-is, though it may require the fix I just pushed. I don't know how you were even able to run it without `replace-in-string`. Maybe that was in emacs 24 but I can't confirm.

If I'm in a shell session I am often using it in a remote context, so `shstream` is of no help here. However, if you use `sh :session session1` to first start a shell session (or create an `M-x shell` first, then tie it to your org code block), *and then* ssh into a remote machine, your code blocks work magically against the remote machine. With kaz-yos's `eval-in-repl` it is very powerful.

The main drawback is that it is a chore to copy stdout when you need it. For me, that's about 10% of the time.

Please retest and reopen a new issue if necessary. I can't promise a timely response though.
